### ISSUE TITLE
Error when authenticating with Substack

### ISSUE THREAD

**Issue by adaptiman** [jwoglom/remarkable-substack#7]
During the process of authenticating for the first time with Substack, I get the following trace and call stack:

`
Traceback (most recent call last):
  File "/home/appuser/main.py", line 242, in <module>
    main(args)
  File "/home/appuser/main.py", line 55, in main
    ls = rm.ls(args.folder)
  File "/home/appuser/remarkable.py", line 55, in ls
    raise RuntimeError(f"Couldn't run ls: exit code {out.returncode}: {out.stdout} {out.stderr}")

RuntimeError: Couldn't run ls: exit code 1: b'' b'ERROR: 2024/09/21 04:42:09 main.go:77: failed to build documents tree, last error: request failed with status 410\n'
`
The code at line 55 in remarkable.py indicates a failure when issueing the ls command. Perhaps something in the Substack api has changed?

**Comment by adaptiman** [comment]
@jwoglom bump

Dead in the water.

**Comment by jwoglom** [comment]
Hm, unfortunately I'm also seeing this. Looks to be widespread: https://old.reddit.com/r/RemarkableTablet/comments/1fj86xz/has_remarkable_broken_their_cloud_api/

**Comment by adaptiman** [comment]
Where did you get your original knowledge of the Substack API? Do they, or does someone else publish it?


--
Chat with me NOW via MS ***@***.***>
Book a time with ***@***.***/meetingtype/SVRwCe7HMUGxuT6WGxi68g2?anonymous&ep=mLinkFromTile>

David S. Sweeney, '88
Texas A&M University
***@***.******@***.***>

________________________________

**Comment by jwoglom** [comment]
it's unfortunately private, and has just been reverse-engineered by various members of the community. Looks like there's a partially working javascript version right now, so might have to see about trying to port the fixes to the python library i'm using here

**Comment by adaptiman** [comment]
I don't know that I can help you with the coding but I'm certainly happy to test it.


--
Chat with me NOW via MS ***@***.***>
Book a time with ***@***.***/meetingtype/SVRwCe7HMUGxuT6WGxi68g2?anonymous&ep=mLinkFromTile>

David S. Sweeney, '88
Texas A&M University
***@***.******@***.***>

________________________________
